
@api_url={{$dotenv APP_URL}}:{{$dotenv APP_PORT}}

@contentType = application/json

@commonPassword = "YourP@ssw0rd!"

# criar usuario
@accountUserFirstName = "ricardo"
@accountUserLastName = "martins"
@accountUserName = "ricardo.martins"
@accountUserEmail = "email@teste.com"
@beareToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3MTkxNjEzOTgsImV4cCI6MTcxOTE2NDk5OCwibmJmIjoxNzE5MTYxMzk4LCJqdGkiOiJPTEF3cng2Yktjb1RSdmRQIiwic3ViIjoiMSIsInBydiI6IjAwYmVjMDEwYzEzYjAxODY1NDBlYTk2YjI3YzFkYzEwOGI1OGQyNDAifQ.H2STmf2g7KE55H99-8KRcoCD_yUAkMTr3A9u98K2F7E"

### Api Home

GET {{api_url}}/api
Content-Type: {{contentType}}

### Health-check

GET {{api_url}}/api/health-check
Accept: {{contentType}}
Content-Type: {{contentType}}


### Autenticar usuário criado no SEED
POST {{api_url}}/api/auth/login
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "email": "email@tests.com",
    "password": {{commonPassword}}
}


### Me
GET {{api_url}}/api/v1/me
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

### Logout

POST {{api_url}}/api/auth/logout
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}






### Registrar novo usuário
POST {{api_url}}/api/auth/register
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "first_name": {{accountUserFirstName}},
    "last_name": {{accountUserLastName}},
    "username": {{accountUserName}},
    "email": {{accountUserEmail}},
    "password": {{commonPassword}}
}

### Autenticar usuário criado anteriormente
POST {{api_url}}/api/auth/login
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "email": "email@teste.com",
    "password": "YourP@ssw0rd"
}

### Logout
POST {{api_url}}/api/auth/logout
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### TEAM List
GET {{api_url}}/api/v1/teams
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### TEAM create
POST {{api_url}}/api/v1/teams
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "conference": "West",
    "division": "Southwest",
    "city": "Los Angeles",
    "name": "Raptors",
    "full_name": "Portland Trail Blazers",
    "abbreviation": "PTB"
}


### TEAM read
GET {{api_url}}/api/v1/teams/45
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### TEAM update
PUT {{api_url}}/api/v1/teams/45
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "conference": "Mid-East",
    "division": "Northwest"
}


### TEAM delete

DELETE {{api_url}}/api/v1/teams/45
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### TEAM Find
GET {{api_url}}/api/v1/teams?q=Bu
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}




### PLAYER List
GET {{api_url}}/api/v1/players
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### PLAYER create
POST {{api_url}}/api/v1/players
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "first_name": "Ricardo",
    "last_name": "Martins",
    "position": "G",
    "height": "6-6",
    "weight": "190",
    "jersey_number": "8",
    "college": "Engenharia",
    "country": "Spain",
    "draft_year": 2013,
    "draft_round": 2,
    "draft_number": 32,
    "team_id": 1
}


### PLAYER read
GET {{api_url}}/api/v1/players/2
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### PLAYER update
PUT {{api_url}}/api/v1/players/1
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "first_name": "Jogador",
    "last_name": "numero 1"
}


### PLAYER delete

DELETE {{api_url}}/api/v1/players/1
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### PLAYER Find
GET {{api_url}}/api/v1/players?q=eng
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}





### GAME List
GET {{api_url}}/api/v1/games
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### GAME create
POST {{api_url}}/api/v1/games
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
      "date": "2023-10-24",
      "season": 2023,
      "status": "Final",
      "period": 4,
      "time": "Final",
      "postseason": false,
      "home_team_score": 104,
      "visitor_team_score": 108,
      "team_home_id": 1,
      "team_visitor_id": 2
}


### GAME read
GET {{api_url}}/api/v1/games/2
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### GAME update
PUT {{api_url}}/api/v1/games/1
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "season": 2024,
}


### GAME delete

DELETE {{api_url}}/api/v1/games/1
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### GAME Find
GET {{api_url}}/api/v1/games?q=eng&season=2023
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}






### USER List
GET {{api_url}}/api/v1/users
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### USER create
POST {{api_url}}/api/v1/users
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "first_name": "admin",
    "last_name": "test",
    "username": "admin",
    "email": "test@email.com",
    "password": "pass"
}


### USER read
GET {{api_url}}/api/v1/users/3
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### USER update
PUT {{api_url}}/api/v1/users/3
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}

{
    "username": "admin.test",
}


### USER delete

DELETE {{api_url}}/api/v1/users/3
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}


### USER Find
GET {{api_url}}/api/v1/users?q=test
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Authorization: {{beareToken}}